default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: postgres
  username: postgres.olvlqtuxojixlowgsldc
  password: 3WMvjH7jR3D99pEp
  host: aws-0-ap-southeast-1.pooler.supabase.com
  port: 6543

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
