development:
  adapter: async

test:
  adapter: test

production:
  adapter: async
  allowed_request_origins:
    - "https://chatrooms-production-app-e359b4390f7a.herokuapp.com"
  channel_prefix: chatroom_production
